### ISSUE TITLE
Lister les freelancers 

### ISSUE THREAD

**Issue by walidmh** [PERHAPS-4IW3/Perhaps#17]
En tant qu'utilisateur ou visiteur du site, je souhaite voir la liste des différents freelancers inscrit sur le site sur la page “Freelancer” afin de lister les différents freelancers et ainsi voir leur page détail.

RG-1: Tous les visiteurs pourront avoir accès à la page d’accueil et à la page “Freelancer”.
RG-2: Afficher au maximum 16 freelancers sur la page”Freelancer”.
RG-3: Tous les visiteurs du site pourront voir la liste des freelancer, cliquer sur un freelancer et voir sa fiche en détail.

CA-1: Etant donné que je suis visiteur ou utilisateur du site alors je dois avoir accès à l’onglet « Freelancer » qui listera les Freelancers inscrit sur le site.
CA-2: Etant donné que je suis visiteur ou utilisateur du site alors je peux voir la liste des “Freelancers” et leur page détail.

**Comment by Muhammad-Tounsi** [comment]
Task done
