### ISSUE TITLE
Rechercher les projets sur le site

### ISSUE THREAD

**Issue by walidmh** [PERHAPS-4IW3/Perhaps#20]
En tant qu'utilisateur ou visiteur du site, je peux rechercher des projets déposés sur le site en mettant des filtres en place afin de pouvoir trouver plus vite un projet.

RG-1: Tous les visiteurs pourront avoir accès à la page d’accueil et à la page “Projet”.
RG-2: Tous les visiteurs du site pourront voir la liste des projets et les rechercher via une barre de recherche.
RG-3: Tous les visiteurs pourront cliquer sur le projet et voir sa fiche en détail.

CA-1: Etant donné que je suis visiteur ou utilisateur du site alors je dois avoir accès à l’onglet « Projets » qui listera les projets créés.
CA-2: Etant donné que je suis visiteur ou utilisateur du site alors je peux utiliser la barre de recherche pour trouver des projets en fonction de ma recherche.

**Comment by Muhammad-Tounsi** [comment]
Task done
