### ISSUE TITLE
Module Inscription 

### ISSUE THREAD

**Issue by walidmh** [PERHAPS-4IW3/Perhaps#24]
En tant que "Porteur de Projet" ou "Freelancer", je souhaite pouvoir m'inscrire sur le site afin d’avoir accès à mon espace personnel, modifier mes informations, gérer mes projets, ...

RG-1: Tous les utilisateurs peuvent voir le bouton « Inscription ».
RG-2: Seul les « Porteurs de Projet » et les Freelancer peuvent s’inscrire.
RG-3: Pour l’inscription, les champs suivants seront obligatoires pour les deux types d’utilisateur : type de profil, email, mot de passe, prénom, nom, adresse, ville, CP, Pays, téléphone.
RG-4: Pour l’inscription, les champs suivants seront obligatoires pour les Freelancer seulement : statut, tarif horaire, présentation, compétences (au moins une) et nom de la société. 
RG-5: Le champ tarif Horaire devra être supérieur à 0€ et le champ email devra être de type email.

CA-1: Étant donné que je suis visiteur alors je peux avoir accès au bouton “Inscription” et au formulaire d’inscription. 
CA-2: Étant donné que je suis Porteur de projet ou Freelancer et que je remplis mal mon formulaire alors j’aurai un message d’erreur.
CA-3: Étant donné que je suis Porteur de projet ou Freelancer et que je remplis bien mon formulaire alors j’aurai un message de validation.

**Comment by Muhammad-Tounsi** [comment]
Finir le formulaire pour les freelancers
