### ISSUE TITLE
Validation email à l'inscription

### ISSUE THREAD

**Issue by walidmh** [PERHAPS-4IW3/Perhaps#26]
En tant que "Porteur de Projet" ou "Freelancer", je dois recevoir un mail du site pour valider mon email afin de confirmer que l’adresse existe et afin d’avoir accès à mon espace personnel.

RG-1: Dès la fin de mon inscription, je dois recevoir un mail pour confirmer mon adresse email.
RG-2: Seul les « Porteurs de Projet » et les Freelancer inscrit peuvent recevoir un mail de validation d’email.

CA-1: Étant donné que je suis Porteur de projet ou Freelancer et que je me suis bien inscrit sur le site alors je dois recevoir un mail de validation d’email avec un lien redirigeant vers le site.
CA-2: Étant donné que je suis Porteur de projet ou Freelancer et que je valide bien mon email alors je dois voir un message de validation à mon retour sur le site.
CA-3: Étant donné que je suis Porteur de projet ou Freelancer et que je ne valide pas mon email alors à mon retour sur le site je dois voir un message “Attention”.

**Comment by Muhammad-Tounsi** [comment]
Task DONE
