### ISSUE TITLE
Un freelancer postule à un projet.

### ISSUE THREAD

**Issue by walidmh** [PERHAPS-4IW3/Perhaps#30]
En tant que Freelancer inscrit sur le site, je souhaite postuler à un projet visible sur la page d’accueil ou sur la page « Projet » en cliquant sur un bouton « Postuler » afin de pouvoir réaliser le projet.

RG-1: Seul les Freelancers pourront voir le bouton “Postuler” sur la page détail d’un projet.
RG-2: Seul les Freelancers pourront postuler à un projet.
RG-3: Dès qu’un Freelancer aura postulé à un projet, une nouvelle page s’affichera pour fournir différents éléments et valider cette postulation.

CA-1: Etant donné que je suis un Freelancer alors je dois voir l’ensemble des projets créés sur le site et pouvoir accéder à leur page détail.
CA-2: Etant donné que je suis un Freelancer alors je dois voir le bouton “Postuler” sur la fiche détail des projets.
CA-3: Etant donné que je suis un Freelancer alors je peux postuler à un projet et avoir un message de confirmation.

**Comment by Muhammad-Tounsi** [comment]
Task done
